# Generated by Django 5.1.4 on 2025-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='secret',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
