# Generated by Django 5.1.4 on 2025-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0002_bankaccount_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='secret_id',
            field=models.UUIDField(null=True),
        ),
    ]
