# Generated by Django 5.1.4 on 2025-01-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0004_spendingcategory_default_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('TR', 'Transaction'), ('AC', 'Account'), ('BU', 'Budget'), ('GE', 'General')], default='GE', max_length=2),
        ),
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('bank_token_id', models.UUIDField(editable=False)),
                ('code', models.CharField(editable=False, max_length=128)),
                ('created_at', models.DateTimeField(editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('activated', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ET_HOME.bankaccount')),
            ],
        ),
    ]
