# Generated by Django 5.1.4 on 2025-01-27 12:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0005_spendingcategory_is_active_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction_id',
            field=models.UUIDField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='apptoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='apptoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
