# Generated by Django 5.1.4 on 2025-01-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0006_transaction_bank_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='bank_token_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_transaction_id',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
