# Generated by Django 5.1.4 on 2025-01-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0007_alter_apptoken_bank_token_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ET_HOME.spendingcategory'),
        ),
    ]
