# Generated by Django 5.1.4 on 2025-01-29 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0008_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendingcategory',
            unique_together={('name', 'user')},
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='user_budget',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='spendingcategory',
            name='default_budget',
        ),
        migrations.RemoveField(
            model_name='spendingcategory',
            name='is_active',
        ),
    ]
