# Generated by Django 5.1.4 on 2025-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0009_alter_spendingcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcategory',
            name='trigger_notification',
            field=models.BooleanField(default=True),
        ),
    ]
