# Generated by Django 5.1.4 on 2025-01-29 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_user_default(apps, schema_editor):
    Transaction = apps.get_model("ET_HOME", "Transaction")
    for transaction in Transaction.objects.all().iterator():
        transaction.user = transaction.account.user
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0009_alter_spendingcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(set_user_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ET_HOME.bankaccount'),
        ),
    ]
