# Generated by Django 5.1.4 on 2025-02-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0010_spendingcategory_trigger_notification'),
        ('ET_HOME', '0010_transaction_user_alter_transaction_account'),
    ]

    operations = [
    ]
