# Generated by Django 5.1.4 on 2025-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0012_bankaccount_added_at_spendingcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
