# Generated by Django 5.1.4 on 2025-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET_HOME', '0013_alter_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_activated',
            field=models.BooleanField(default=False),
        ),
    ]
